# Generated by Django 4.1.1 on 2024-07-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('dyr', models.TextField(verbose_name='Details of your requirement')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('school', 'Preschool, Kindergarten, KG, Nursery'), ('g2', 'Grade 2'), ('g1', 'Grade 1'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5'), ('g6', 'Grade 6'), ('g7', 'Grade 7'), ('g8', 'Grade 8'), ('g9', 'Grade 9'), ('g10', 'Grade 10'), ('IGCSE', 'IGCSE'), ('GCSE', 'GCSE'), ('O_level', 'O level'), ('g11', 'Grade 11'), ('AS_level', 'AS level'), ('A2_level', 'A2 level'), ('A_level', 'A level'), ('g12', 'Grade 12'), ('Diploma', 'Diploma'), ('Bachelors/Undergraduate', 'Bachelors/Undergraduate'), ('Masters/Postgraduate', 'Masters/Postgraduate'), ('MPhil', 'MPhil'), ('Doctorate/PhD', 'Doctorate/PhD')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('i_want', models.CharField(choices=[('tutoring', 'Tutoring'), ('assignment_help', 'Assignment Help')], max_length=50)),
                ('meeting_option_online', models.BooleanField(default=False)),
                ('meeting_option_my_place', models.BooleanField(default=False)),
                ('meeting_option_tutors_place', models.BooleanField(default=False)),
                ('budget', models.CharField(max_length=255)),
                ('budget_need', models.CharField(choices=[('per_hour', 'per hour'), ('per_day', 'per day'), ('per_week', 'per week'), ('per_month', 'per month')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10)),
                ('language', models.CharField(max_length=255)),
                ('tutor_want', models.CharField(choices=[('one', 'only one'), ('two', 'only two'), ('more', 'As many as possible')], max_length=10)),
                ('need', models.CharField(choices=[('part_time', 'Part time'), ('full_time', 'Full time')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
