# Generated by Django 4.1.1 on 2024-07-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
