# Generated by Django 4.1.1 on 2024-07-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0002_tutorrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
