# Generated by Django 4.1.1 on 2024-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0003_tutorrequest_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorrequest',
            name='meeting_option_my_place',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='meeting_option_online',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='meeting_option_tutors_place',
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='meeting_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
