# Generated by Django 4.1.1 on 2024-08-17 09:26

from django.db import migrations, models
import kovai_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0007_tutorregistration_otp_tutorregistration_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorregistration',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to=kovai_app.models.upload_to),
        ),
    ]
