# Generated by Django 4.1.1 on 2024-08-17 16:28

from django.db import migrations, models
import kovai_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0008_alter_tutorregistration_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorregistration',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=kovai_app.models.upload_to),
        ),
    ]
