# Generated by Django 4.1.1 on 2024-08-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0009_alter_tutorregistration_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorregistration',
            name='filename',
            field=models.CharField(blank=True, choices=[('online_teaching', 'Online teaching'), ('offline_teaching', 'Offline teaching'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('both', 'Both')], max_length=20, null=True),
        ),
    ]
