# Generated by Django 4.1.1 on 2024-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0010_tutorregistration_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorregistration',
            name='job_roll',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
