# Generated by Django 4.1.1 on 2024-08-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0011_tutorregistration_job_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorregistration',
            name='language',
            field=models.CharField(blank=True, choices=[('individual_teaching', 'Individual Teaching'), ('teaching_company', 'Teaching Company')], max_length=50, null=True),
        ),
    ]
