# Generated by Django 4.1.1 on 2024-08-23 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0013_tutorregistration_five_from_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='dates',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
