# Generated by Django 4.1.1 on 2024-08-24 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0014_tutorrequest_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('school', 'Preschool, Kindergarten, KG, Nursery'), ('g2', 'Grade 2'), ('g1', 'Grade 1'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5'), ('g6', 'Grade 6'), ('g7', 'Grade 7'), ('g8', 'Grade 8'), ('g9', 'Grade 9'), ('g10', 'Grade 10'), ('IGCSE', 'IGCSE'), ('GCSE', 'GCSE'), ('O_level', 'O level'), ('g11', 'Grade 11'), ('AS_level', 'AS level'), ('A2_level', 'A2 level'), ('A_level', 'A level'), ('g12', 'Grade 12'), ('Diploma', 'Diploma'), ('Bachelors/Undergraduate', 'Bachelors/Undergraduate'), ('Masters/Postgraduate', 'Masters/Postgraduate'), ('MPhil', 'MPhil'), ('Doctorate/PhD', 'Doctorate/PhD')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('i_want', models.CharField(choices=[('tutoring', 'Tutoring'), ('assignment_help', 'Assignment Help')], max_length=50)),
                ('meeting_option', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(max_length=255)),
                ('budget_need', models.CharField(choices=[('per_hour', 'per hour'), ('per_day', 'per day'), ('per_week', 'per week'), ('per_month', 'per month')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10)),
                ('language', models.CharField(max_length=255)),
                ('tutor_want', models.CharField(choices=[('one', 'only one'), ('two', 'only two'), ('more', 'As many as possible')], max_length=10)),
                ('need', models.CharField(choices=[('part_time', 'Part time'), ('full_time', 'Full time')], max_length=10)),
                ('message', models.TextField()),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='budget_need',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='i_want',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='meeting_option',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='need',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='tutor_want',
        ),
    ]
