# Generated by Django 4.1.1 on 2024-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0015_requestpost_remove_tutorrequest_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpost',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='requestpost',
            name='password',
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
