# Generated by Django 4.1.1 on 2024-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0016_remove_requestpost_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorrequest',
            name='dyr',
        ),
        migrations.AddField(
            model_name='requestpost',
            name='dyr',
            field=models.TextField(blank=True, null=True, verbose_name='Details of your requirement'),
        ),
    ]
