# Generated by Django 4.1.1 on 2024-08-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0017_remove_tutorrequest_dyr_requestpost_dyr'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpost',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
