# Generated by Django 4.1.1 on 2024-08-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0021_remove_tutorrequest_gender_requestpost_five_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
