# Generated by Django 4.1.1 on 2024-09-05 07:25

from django.db import migrations, models
import kovai_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0022_requestpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpost',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestpost',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=kovai_app.models.upload_to_stu),
        ),
    ]
