# Generated by Django 4.1.1 on 2024-09-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0023_requestpost_filename_requestpost_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpost',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorregistration',
            name='filename',
            field=models.CharField(blank=True, choices=[('online_teaching', 'Online teaching'), ('offline_teaching', 'Offline teaching'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('both', 'Both')], max_length=200, null=True),
        ),
    ]
