# Generated by Django 4.1.1 on 2024-09-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0024_alter_requestpost_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpost',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
