# Generated by Django 4.1.1 on 2024-09-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0025_requestpost_coin_tutorregistration_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_addcard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('cid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_addcard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
