# Generated by Django 4.1.1 on 2024-09-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0026_student_addcard_teacher_addcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_addcard',
            name='cid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
