# Generated by Django 4.1.1 on 2024-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0027_teacher_addcard_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='w_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
