# Generated by Django 4.1.1 on 2024-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0028_tutorrequest_w_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
