# Generated by Django 4.1.1 on 2024-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0030_alter_tutorregistration_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorregistration',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='s_profile_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
