# Generated by Django 4.1.1 on 2024-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0031_tutorregistration_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='five_from_level',
            new_name='degree_name_five',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='five_subject',
            new_name='degree_name_four',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='five_to_level',
            new_name='degree_name_three',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='four_from_level',
            new_name='degree_name_two',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='four_subject',
            new_name='institution_name_five',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='four_to_level',
            new_name='institution_name_four',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='three_from_level',
            new_name='institution_name_three',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='three_subject',
            new_name='institution_name_two',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='three_to_level',
            new_name='specialisation',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='to_level',
            new_name='specialisation_five',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='two_from_level',
            new_name='specialisation_four',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='two_subject',
            new_name='specialisation_three',
        ),
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='two_to_level',
            new_name='specialisation_two',
        ),
        migrations.RemoveField(
            model_name='tutorregistration',
            name='association',
        ),
        migrations.RemoveField(
            model_name='tutorregistration',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tutorregistration',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='degree_type_five',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Higher_Secondary', 'Higher Secondary'), ('Diploma', 'Diploma'), ('Graduation', 'Graduation'), ('AdvancedDiploma', 'Advanced Diploma'), ('PostGraduation', 'Post Graduation'), ('Doctorate/PhD', 'Doctorate/PhD'), ('Certification', 'Certification'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='degree_type_four',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Higher_Secondary', 'Higher Secondary'), ('Diploma', 'Diploma'), ('Graduation', 'Graduation'), ('AdvancedDiploma', 'Advanced Diploma'), ('PostGraduation', 'Post Graduation'), ('Doctorate/PhD', 'Doctorate/PhD'), ('Certification', 'Certification'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='degree_type_three',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Higher_Secondary', 'Higher Secondary'), ('Diploma', 'Diploma'), ('Graduation', 'Graduation'), ('AdvancedDiploma', 'Advanced Diploma'), ('PostGraduation', 'Post Graduation'), ('Doctorate/PhD', 'Doctorate/PhD'), ('Certification', 'Certification'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='degree_type_two',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Higher_Secondary', 'Higher Secondary'), ('Diploma', 'Diploma'), ('Graduation', 'Graduation'), ('AdvancedDiploma', 'Advanced Diploma'), ('PostGraduation', 'Post Graduation'), ('Doctorate/PhD', 'Doctorate/PhD'), ('Certification', 'Certification'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
