# Generated by Django 4.1.1 on 2024-11-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0032_rename_five_from_level_tutorregistration_degree_name_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorregistration',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='tutorregistration',
            name='job_end_date',
        ),
        migrations.RemoveField(
            model_name='tutorregistration',
            name='job_start_date',
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='company_name_five',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='company_name_four',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='company_name_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='company_name_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='job_roll_five',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='job_roll_four',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='job_roll_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='job_roll_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='year_of_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='year_of_experience_five',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='year_of_experience_four',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='year_of_experience_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='year_of_experience_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
