# Generated by Django 4.1.1 on 2024-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0033_remove_tutorregistration_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorregistration',
            name='online_experience',
        ),
        migrations.RemoveField(
            model_name='tutorregistration',
            name='teaching_experience',
        ),
        migrations.RemoveField(
            model_name='tutorregistration',
            name='total_experience',
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='classes',
            field=models.CharField(blank=True, choices=[('per_hour', 'per hour'), ('per_month', 'per month'), ('per_year', 'per year')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('per_hour', 'per hour'), ('per_month', 'per month'), ('per_year', 'per year')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='language_five',
            field=models.CharField(blank=True, choices=[('individual_teaching', 'Individual Teaching'), ('teaching_company', 'Teaching Company')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='language_four',
            field=models.CharField(blank=True, choices=[('individual_teaching', 'Individual Teaching'), ('teaching_company', 'Teaching Company')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='language_subject',
            field=models.CharField(blank=True, choices=[('per_hour', 'per hour'), ('per_month', 'per month'), ('per_year', 'per year')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='language_three',
            field=models.CharField(blank=True, choices=[('individual_teaching', 'Individual Teaching'), ('teaching_company', 'Teaching Company')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='language_two',
            field=models.CharField(blank=True, choices=[('individual_teaching', 'Individual Teaching'), ('teaching_company', 'Teaching Company')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorregistration',
            name='other_subject',
            field=models.CharField(blank=True, choices=[('per_hour', 'per hour'), ('per_month', 'per month'), ('per_year', 'per year')], max_length=20, null=True),
        ),
    ]
