# Generated by Django 4.1.1 on 2024-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0035_tutorrequest_gender_tutorrequest_mobile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpost',
            name='classes',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='requestpost',
            name='curriculum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
