# Generated by Django 4.1.1 on 2024-12-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0036_requestpost_classes_requestpost_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpost',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestpost',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('school', 'Preschool, Kindergarten, KG, Nursery'), ('g2', 'Grade 2'), ('g1', 'Grade 1'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5'), ('g6', 'Grade 6'), ('g7', 'Grade 7'), ('g8', 'Grade 8'), ('g9', 'Grade 9'), ('g10', 'Grade 10'), ('IGCSE', 'IGCSE'), ('GCSE', 'GCSE'), ('O_level', 'O level'), ('g11', 'Grade 11'), ('AS_level', 'AS level'), ('A2_level', 'A2 level'), ('A_level', 'A level'), ('g12', 'Grade 12'), ('Diploma', 'Diploma'), ('Bachelors/Undergraduate', 'Bachelors/Undergraduate'), ('Masters/Postgraduate', 'Masters/Postgraduate'), ('MPhil', 'MPhil'), ('Doctorate/PhD', 'Doctorate/PhD')], max_length=50, null=True),
        ),
    ]
