# Generated by Django 4.1.1 on 2024-12-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0037_alter_requestpost_language_alter_requestpost_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpost',
            name='message',
        ),
    ]
