# Generated by Django 4.1.1 on 2024-12-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0038_remove_requestpost_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpost',
            name='tutor_want',
        ),
    ]
