# Generated by Django 4.1.1 on 2024-12-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0039_remove_requestpost_tutor_want'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpost',
            name='level',
        ),
    ]
