# Generated by Django 4.1.1 on 2024-12-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0040_remove_requestpost_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpost',
            name='imagess',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
