# Generated by Django 4.1.1 on 2024-12-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0041_requestpost_imagess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorregistration',
            old_name='otp',
            new_name='email_otp',
        ),
    ]
