# Generated by Django 4.1.1 on 2025-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0043_tutorregistration_user_tutorrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpost',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
