# Generated by Django 4.1.1 on 2025-04-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kovai_app', '0045_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
